import express from 'express';
import { YemotRouter, ExitError } from 'yemot-router2';
import { GoogleGenerativeAI } from '@google/generative-ai';
import YemotApi from 'yemot-api';
if (process.loadEnvFile) { try { process.loadEnvFile(); } catch {} }
const app=express(); app.use(express.urlencoded({extended:true})); app.use(express.json());
const apiKeys=(process.env.GEMINI_API_KEYS||process.env.GEMINI_API_KEY||'').split(',').map(x=>x.trim()).filter(Boolean);
const MODEL_NAMES=(process.env.GEMINI_MODELS||'gemini-3-flash-preview,gemini-3.8-flash,gemini-3.6-flash,gemini-3.5-flash,gemini-3.5-flash-lite').split(',').map(x=>x.trim()).filter(Boolean);
const REQUEST_TIMEOUT_MS=Number(process.env.REQUEST_TIMEOUT_MS||55000),PER_MODEL_TIMEOUT_MS=Number(process.env.PER_MODEL_TIMEOUT_MS||20000),COOLDOWN_MS=Number(process.env.MODEL_COOLDOWN_MS||3600000),DASHBOARD_PASSWORD=String(process.env.DASHBOARD_PASSWORD||'1234');
const FILTER='כלל סינון: אין לספק תוכן מיני או אירוטי, פורנוגרפיה, עירום מיני, אלימות גרפית, סמים, הימורים או פגיעה עצמית. אם השאלה דורשת תוכן אסור החזר בדיוק: היי עצור הקו מסונן ולא ניתן לדבר איתו על תוכן שאינו מתאים לערכי הצניעות והחינוך';
const SYSTEM=[FILTER,process.env.AI_SYSTEM_INSTRUCTION||''].filter(Boolean).join('\n\n');
const clients=apiKeys.map(k=>new GoogleGenerativeAI(k)),models=MODEL_NAMES.map(n=>clients.map(c=>c.getGenerativeModel({model:n}))),webModels=MODEL_NAMES.map(n=>clients.map(c=>c.getGenerativeModel({model:n,tools:[{googleSearch:{}}]})));
const cooldowns=new Map(),conversations=[],activeCalls=new Map();
const router=YemotRouter({printLog:true,timeout:120000,defaults:{removeInvalidChars:true},uncaughtErrorHandler:e=>console.error('YEMOT:',e)});
function timeout(p,ms,label){let t;const q=new Promise((_,rej)=>{t=setTimeout(()=>{const e=new Error('Timeout: '+label);e.status=408;rej(e)},ms)});return Promise.race([p,q]).finally(()=>clearTimeout(t))}
async function generate(contents,web=false){if(!models.length||!models[0]?.length)throw Object.assign(new Error('Gemini is not configured'),{status:400});const groups=web?webModels:models;let last;for(let mi=0;mi<groups.length;mi++)for(let ki=0;ki<groups[mi].length;ki++){const key=MODEL_NAMES[mi]+':'+ki;if((cooldowns.get(key)||0)>Date.now())continue;try{const r=await timeout(groups[mi][ki].generateContent(contents),PER_MODEL_TIMEOUT_MS,MODEL_NAMES[mi]);cooldowns.delete(key);return r}catch(e){last=e;if(String(e.status||e.message).includes('429')||String(e.message).toLowerCase().includes('quota'))cooldowns.set(key,Date.now()+COOLDOWN_MS)}}if(!last){cooldowns.clear();return generate(contents,web)}throw last}
function clean(t){return String(t||'').replace(/[*#_~]/g,' ').replace(/[\[\]()<>]/g,' ').replace(/[."“”‘’']/g,' ').replace(/[-–—]/g,' ').replace(/\s+/g,' ').trim()}
function limitWords(t,max=50){const s=String(t||'').trim();return s.split(/\s+/).slice(0,max).join('')}
function callerPhone(c){return String(c?.values?.ApiPhone??c?.req?.query?.ApiPhone??c?.req?.body?.ApiPhone??'').trim()||'לא מזוהה'}
async function downloadRecording(path){const p=path.startsWith('ivr2:')?path:'ivr2:'+path,token=String(process.env.YEMOT_API_KEY||'').trim();if(token){const u='https://www.call2all.co.il/ym/api/DownloadFile?token='+encodeURIComponent(token)+'&path='+encodeURIComponent(p),r=await timeout(fetch(u),REQUEST_TIMEOUT_MS,'download recording');if(!r.ok)throw new Error('DownloadFile HTTP '+r.status);return Buffer.from(await r.arrayBuffer())}if(process.env.YEMOT_API_USERNAME&&process.env.YEMOT_API_PASSWORD){const api=new YemotApi(process.env.YEMOT_API_USERNAME,process.env.YEMOT_API_PASSWORD),r=await timeout(api.download_file(p),REQUEST_TIMEOUT_MS,'download recording');return Buffer.isBuffer(r.data)?r.data:Buffer.from(r.data)}throw new Error('YEMOT credentials are missing')}
async function answerAudio(buf,history){const audio={inlineData:{mimeType:process.env.YEMOT_AUDIO_MIME_TYPE||'audio/wav',data:buf.toString('base64')}},hist=history.length?'\nהיסטוריית שיחה:\n'+history.map((x,i)=>'סבב '+(i+1)+': מתקשר: '+x.user+' | AI: '+x.reply).join('\n'):'';const prompt=SYSTEM+hist+'\nהאזן להקלטה. הבן את השאלה ותן תשובה קצרה וטבעית להקראה בטלפון. ענה בשפת המתקשר. ללא Markdown. חובה: התשובה reply תהיה לכל היותר 50 מילים. החזר JSON בלבד: {"transcript":"...","reply":"..."}. אם נדרש מידע עדכני באינטרנט, התחל את reply ב-SEARCH_REQUEST.';const r=await generate([audio,{text:prompt}]),raw=r.response.text().trim();try{const j=JSON.parse(raw);return{transcript:clean(j.transcript||'הקלטה'),reply:j.reply||''}}catch{return{transcript:'הקלטת קול',reply:raw}}}
async function callHandler(call){const p=callerPhone(call),id=String(call?.callId||call?.values?.ApiCallId||Date.now()+'-'+p);activeCalls.set(id,{phone:p,callId:id,lastActivity:Date.now()});console.log(`[CALL ${id}] started phone=${p}`);const history=[];try{let first=true;while(true){const msg=first?clean(process.env.WELCOME_MESSAGE||'שלום וברוכים הבאים לקו הטלפון האישי עם בינה מלאכותית. אנא אמור את שאלתך אחרי הצפצוף ולסיום הקש סולמית'):'אמור שאלה נוספת ולסיום הקש סולמית או כוכבית ליציאה';first=false;console.log(`[CALL ${id}] waiting for recording`);const path=await call.read([{type:'text',data:msg}],'record',{min_length:1,no_confirm_menu:true,max_length:60});console.log(`[CALL ${id}] recording path=${path}`);if(!path||path==='None')return call.id_list_message([{type:'text',data:'תודה רבה ולהתראות'}]);let buf;try{buf=await downloadRecording(path);console.log(`[CALL ${id}] recording downloaded bytes=${buf?.length||0}`)}catch(e){console.error(`[CALL ${id}] recording download failed`,e);await call.id_list_message([{type:'text',data:'תקלה בהורדת ההקלטה נסה שוב'}],{prependToNextAction:true});continue}if(!buf||buf.length<500){await call.id_list_message([{type:'text',data:'לא שמעתי שאלה אנא נסה שוב'}],{prependToNextAction:true});continue}let out;try{out=await answerAudio(buf,history);console.log(`[CALL ${id}] Gemini reply ready transcript=${JSON.stringify(out.transcript)}`);if(out.reply.startsWith('SEARCH_REQUEST')){const r=await generate([{inlineData:{mimeType:process.env.YEMOT_AUDIO_MIME_TYPE||'audio/wav',data:buf.toString('base64')}},{text:SYSTEM+'\nחפש מידע עדכני באינטרנט בנושא: '+out.reply.replace('SEARCH_REQUEST','')+'\nענה קצר וברור בעברית.'}],true);out.reply=r.response.text()}}catch(e){console.error(`[CALL ${id}] Gemini processing failed`,e);out={transcript:'הקלטה',reply:e.status===429?'מצטערים אני עמוס כרגע נסה שוב עוד מעט':e.status===408?'מצטערים לקח יותר מדי זמן לענות נסה שוב':'מצטער הייתה תקלה בעיבוד השאלה אפשר לנסות שוב'}}out.reply=limitWords(clean(out.reply),50)||'מצטער לא הצלחתי לנסח תשובה נסה שוב';history.push({user:out.transcript,reply:out.reply});conversations.push({time:new Date().toISOString(),phone:p,callId:id,user:out.transcript,gemini:out.reply});if(conversations.length>1000)conversations.shift();console.log(`[CALL ${id}] sending reply`);await call.id_list_message([{type:'text',data:out.reply}],{prependToNextAction:true})}}catch(e){console.error(`[CALL ${id}] handler failed`,e);throw e}finally{activeCalls.delete(id);console.log(`[CALL ${id}] ended`)}}
router.all('/yemot',callHandler);app.use('/',router);
function auth(req,res,next){if((req.headers['x-dashboard-key']||req.query.key)!==DASHBOARD_PASSWORD)return res.status(401).json({ok:false});next()}
app.post('/api/verify-auth',(req,res)=>res.json({ok:String(req.body?.password||'')===DASHBOARD_PASSWORD}));
app.get('/api/conversations',auth,(req,res)=>{const callers=[...new Set(conversations.map(x=>x.phone))];res.json({totalMessages:conversations.length,totalCallers:callers.length,activeCalls:[...activeCalls.values()],conversations})});
app.get('/api/logs',auth,(req,res)=>res.json({logs:[]}));
app.post('/api/test-ai',auth,async(req,res)=>{try{const r=await generate([{text:String(req.body?.prompt||'שלום, בדוק תקינות')}]);res.json({ok:true,response:r.response.text()})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.get('/health',(req,res)=>res.json({status:'online',service:'ai-phone-line',models:MODEL_NAMES,geminiConfigured:apiKeys.length>0,yemotConfigured:Boolean(process.env.YEMOT_API_KEY)}));
app.get('/',(req,res)=>res.type('html').send('<!doctype html><html lang="he" dir="rtl"><meta charset="utf-8"><title>AI Phone Line</title><style>body{font-family:Arial;background:#0b1220;color:#fff;max-width:900px;margin:40px auto;padding:20px}.card{background:#111c30;padding:20px;border-radius:14px;margin:12px 0}input,button{padding:10px;margin:5px}</style><div class="card"><h1>קו טלפון אישי עם בינה מלאכותית</h1><p>שרת Gemini + ימות המשיח</p><p><a href="/health" style="color:#6cf">בדיקת שרת</a></p></div></html>'));
process.on('unhandledRejection',e=>{if(!(e instanceof ExitError))console.error(e)});process.on('uncaughtException',e=>{if(!(e instanceof ExitError))console.error(e)});
const port=process.env.PORT||3000;app.listen(port,()=>console.log('Server running on port '+port));